name: Status Checks

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [main, feature/*, hotfix/*, fix/*]

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run flake8
        run: flake8

      - name: Run Mypy
        run: mypy pandaseda
